# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gr4unch3r/windows-test"
  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.inventory_path = "inventory"
  end
end
