# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "guest" do |cfg|
      config.vm.box = "gr4unch3r/windows-10"
      config.vm.box_version = "10.0.17134"
      config.vm.hostname = "guest"
      config.vm.network :private_network, ip: "192.168.56.101", gateway: "192.168.56.100", dns: "192.168.56.100"
      config.vm.synced_folder ".", "/vagrant", disabled: true
      config.vm.provider "virtualbox" do |v, override|
        v.gui = true
        v.name  = "guest"
        v.default_nic_type = "82545EM"
        v.memory = 4096
        v.cpus = 2
        v.customize ["modifyvm", :id, "--vram", "32"]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "./provisioning/guest/playbook.yml"
        ansible.galaxy_role_file = "./provisioning/guest/requirements.yml"
        ansible.inventory_path = "./provisioning/guest/inventory"
      end
    end
    config.vm.define "host" do |cfg|
      config.vm.box = "gr4unch3r/ubuntu-xenial"
      config.vm.hostname = "host"
      config.vm.network :private_network, ip: "192.168.56.100", gateway: "192.168.56.1", dns: "8.8.8.8"
      config.vm.provider "virtualbox" do |v, override|
        v.gui = true
        v.name = "host"
        v.memory = 2048
        v.cpus = 2
        v.customize ["modifyvm", :id, "--vram", "32"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "./provisioning/host/playbook.yml"
        ansible.galaxy_role_file = "./provisioning/host/requirements.yml"
      end
    end
  end
