---
name: CI

on: push

jobs:
  test_dotnet:
    name: test-dotnet-dev
    runs-on: macos-10.15
    env:
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip

      - name: Install Ansible
        run: python3 -m pip install ansible pywinrm

      - name: Test dotnet-dev
        run: vagrant up
        working-directory: dotnet-dev

      - name: Destroy Vagrant box
        run: vagrant destroy -f
        working-directory: dotnet-dev

  test_revcore:
    name: test-revcore-tools
    runs-on: macos-10.15
    env:
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip

      - name: Install Ansible
        run: python3 -m pip install ansible pywinrm

      - name: Test revcore-tools
        run: vagrant up
        working-directory: revcore-tools

      - name: Destroy Vagrant box
        run: vagrant destroy -f
        working-directory: revcore-tools

  build:
    name: jira-issue
    runs-on: ubuntu-latest
    needs: [test_dotnet, test_revcore]
    steps:
      - name: Jira login
        uses: atlassian/gajira-login@master
        if: ${{ always() }}
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue if success
        uses: atlassian/gajira-create@master
        if: ${{ success() }}   
        with:
          project: AVP
          issuetype: Build
          summary: |
            Build completed for ${{ github.repository }}

      - name: Create Jira issue if failed
        uses: atlassian/gajira-create@master
        if: ${{ failure() }}  
        with:
          project: AVP
          issuetype: Build
          summary: |
            Build failed for ${{ github.repository }}
